[versions]

# Plugins
agp = "9.1.0-alpha01"
kotlin = "2.3.0"
protobuf = "0.9.6"
ksp = "2.3.2"

coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.14.0-alpha08"

# LSParanoid
lsparanoid = "0.6.0"

# Xposed
xposed = "82"
xpHelper = "2.9"

# ByteBuddy
byteBuddy = "1.18.2"

# Json
fastjson2 = "2.0.60"

# ProtoBuf
protobuf-javalite = "4.33.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# LSParanoid
lsparanoid = { group = "org.lsposed.lsparanoid", name = "gradle-plugin", version.ref = "lsparanoid" }

# Xposed
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }
xphelper = { group = "com.github.suzhelan", name = "XPHelper", version.ref = "xpHelper" }

# BytyBuddy-Android
byte-buddy-android = { group = "net.bytebuddy", name = "byte-buddy-android", version.ref = "byteBuddy" }

# KSP
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

# Json
fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastjson2" }

# ProtoBuf
protobuf-java-lite = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf-javalite" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
